from __future__ import annotations

from .models import FraudCase


def seeded_cases() -> list[FraudCase]:
    return [
        FraudCase(
            case_id="FRD-INS-001",
            sector="insurance",
            customer_id="CUS-1001",
            customer_name="Seema Agarwal",
            provider_name="Apollo Hospitals",
            policy_number="POL-99321",
            claim_number="CLM-88001",
            claim_amount=582000,
            diagnosis_code="C25.9",
            procedure_code="PROC-ONC-43",
            treatment_date="2026-09-14",
            submitted_at="2026-09-17T08:45:00",
            ip_address="103.44.210.55",
            device_id="DV-AC9921",
            bank_account_hash="ba_a933",
            phone_hash="ph_a113",
            previous_claim_count_30d=2,
            invoice_hash="inv_shared_229",
            document_text="Discharge summary oncology admission with repeated invoice lines and misc fee.",
            is_known_fraud=1,
        ),
        FraudCase(
            case_id="FRD-INS-002",
            sector="insurance",
            customer_id="CUS-1002",
            customer_name="Nitin Rao",
            provider_name="Fortis Care",
            policy_number="POL-44117",
            claim_number="CLM-88002",
            claim_amount=98000,
            diagnosis_code="K35.80",
            procedure_code="PROC-APP-11",
            treatment_date="2026-09-10",
            submitted_at="2026-09-11T10:20:00",
            ip_address="122.11.10.2",
            device_id="DV-LG110",
            bank_account_hash="ba_2211",
            phone_hash="ph_7782",
            previous_claim_count_30d=0,
            invoice_hash="inv_clean_772",
            document_text="Appendectomy claim with complete bills and clean discharge summary.",
            is_known_fraud=0,
        ),
        FraudCase(
            case_id="FRD-INS-003",
            sector="insurance",
            customer_id="CUS-1003",
            customer_name="Ankit S.",
            provider_name="City Trauma Center",
            policy_number="POL-23188",
            claim_number="CLM-88003",
            claim_amount=388000,
            diagnosis_code="S06.0",
            procedure_code="PROC-TRM-91",
            treatment_date="2026-09-13",
            submitted_at="2026-09-13T21:40:00",
            ip_address="103.44.210.55",
            device_id="DV-AC9921",
            bank_account_hash="ba_a933",
            phone_hash="ph_a113",
            previous_claim_count_30d=2,
            invoice_hash="inv_shared_229",
            document_text="Motor claim suspected inflated repair estimate and duplicate parts listing.",
            is_known_fraud=1,
        ),
        FraudCase(
            case_id="FRD-BNK-001",
            sector="banking",
            customer_id="CUS-2001",
            customer_name="Rakesh Verma",
            provider_name="NA",
            policy_number="NA",
            claim_number="TXN-77001",
            claim_amount=145000,
            diagnosis_code="NA",
            procedure_code="NA",
            treatment_date="2026-09-18",
            submitted_at="2026-09-18T07:45:00",
            ip_address="61.8.4.3",
            device_id="DV-BNK-1",
            bank_account_hash="ba_b991",
            phone_hash="ph_b114",
            previous_claim_count_30d=4,
            invoice_hash="",
            document_text="Rapid transfer chain with possible mule account links.",
            is_known_fraud=1,
        ),
    ]

